---

- hosts: htcondor_others
  sudo: yes
  tasks:
  - name: Synchronize dark matter source
    synchronize: src=/usr/local/dark-matter/dark-matter dest=/usr/local/dark-matter delete=yes rsync_timeout=10
